// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!! DO NOT EDIT THIS FILE !!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#pragma once
#include "MiniCppUnit.hpp"
#include <sstream>
#include "ITPDoubleList.hpp"

class ListTest : public TestFixture<ListTest>
{
public:
	TEST_FIXTURE_DESCRIBE(ListTest, "Testing ITPDoubleList...")
	{
		TEST_CASE_DESCRIBE(testDefaultConstructor, "Testing default constructor and size");
		TEST_CASE_DESCRIBE(testInsertFront, "Testing insert_front");
		TEST_CASE_DESCRIBE(testGetFront, "Testing get_front (and insert_front)");
		TEST_CASE_DESCRIBE(testRemoveFront, "Testing remove_front (and insert_front)");
		TEST_CASE_DESCRIBE(testInsertBack, "Testing insert_back");
		TEST_CASE_DESCRIBE(testGetBack, "Testing get_back (and insert_back)");
		TEST_CASE_DESCRIBE(testRemoveBack, "Testing remove_back (and insert_back)");
		TEST_CASE_DESCRIBE(testClear, "Tests the clear function (and insert_front)");
		TEST_CASE_DESCRIBE(testCopyConstructor, "Test the copy constructor (and insert_back)");
		TEST_CASE_DESCRIBE(testAssignment, "Test the assignment operator (and insert_back)");
        	TEST_CASE_DESCRIBE(testIterator, "Tests creating and dereferencing iterator");
        	TEST_CASE_DESCRIBE(testIteratorIncDec, "Tests iterator incrementing / decrementing (pre and post)");
        	TEST_CASE_DESCRIBE(testIteratorInsert, "Tests insert at the iterator");
        	TEST_CASE_DESCRIBE(testIteratorRemove, "Tests remove at the iterator");
    	}
	
	void testDefaultConstructor()
	{
		ITPDoubleList<int> test;
		
		// Make sure the list is constructed with a size of 0
		ASSERT_EQUALS(0U, test.size());

		// This verifies that the head is null
		ASSERT_EQUALS("{}", test.toString());

		// This verifies that the tail is null
		ASSERT_EQUALS("{}", test.toReverseString());
	}

	void testInsertFront()
	{
		ITPDoubleList<int> test;

		for (int i = 0; i < 5; i++)
		{
			test.push_front(i * 5);
		}

		// List should now have a size of 5
		ASSERT_EQUALS(5U, test.size());

		// This verifies the numbers are correct, as well as head of the list
		// and the next pointer of each node
		ASSERT_EQUALS("{20,15,10,5,0}", test.toString());

		// This verifies the tail of the list as well as the prev pointers of each node
		ASSERT_EQUALS("{0,5,10,15,20}", test.toReverseString());
	}

	void testGetFront()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 10; i++)
		{
			test.push_front(i * 3);
			// This is just checking that whatever value we just added to the front
			// is the same value that we get with get_front!
			ASSERT_EQUALS(i * 3, test.front());
			
			// List should now have a size of i + 1
			ASSERT_EQUALS(unsigned(i + 1), test.size());
		}
	}

	void testRemoveFront()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 3; i++)
		{
			test.push_front(i * 7);
		}

		// List should now have a size of 3
		ASSERT_EQUALS(3U, test.size());

		// These should be correct if the inserts worked
		ASSERT_EQUALS("{14,7,0}", test.toString());
		ASSERT_EQUALS("{0,7,14}", test.toReverseString());

		// Try one remove
		test.pop_front();
		// List should now have a size of 2
		ASSERT_EQUALS(2U, test.size());
		// List should now have these values
		ASSERT_EQUALS("{7,0}", test.toString());
		ASSERT_EQUALS("{0,7}", test.toReverseString());

		// Try another remove
		test.pop_front();
		// List should now have a size of 1
		ASSERT_EQUALS(1U, test.size());
		// List should now have these values
		ASSERT_EQUALS("{0}", test.toString());
		ASSERT_EQUALS("{0}", test.toReverseString());

		// Try last remove (both head and tail should be null)
		test.pop_front();
		// List should now have a size of 0
		ASSERT_EQUALS(0U, test.size());
		// List should now be empty
		ASSERT_EQUALS("{}", test.toString());
		ASSERT_EQUALS("{}", test.toReverseString());
	}

	void testInsertBack()
	{
		ITPDoubleList<int> test;

		for (int i = 0; i < 5; i++)
		{
			test.push_back(i * 5);
		}

		// List should now have a size of 5
		ASSERT_EQUALS(5U, test.size());

		// This verifies the numbers are correct, as well as head of the list
		// and the next pointer of each node
		ASSERT_EQUALS("{0,5,10,15,20}", test.toString());

		// This verifies the tail of the list as well as the prev pointers of each node
		ASSERT_EQUALS("{20,15,10,5,0}", test.toReverseString());
	}

	void testGetBack()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 10; i++)
		{
			test.push_back(i * 3);
			// This is just checking that whatever value we just added to the front
			// is the same value that we get with get_back!
			ASSERT_EQUALS(i * 3, test.back());

			// List should now have a size of i + 1
			ASSERT_EQUALS(unsigned(i + 1), test.size());
		}
	}

	void testRemoveBack()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 3; i++)
		{
			test.push_back(i * 7);
		}

		// List should now have a size of 3
		ASSERT_EQUALS(3U, test.size());

		// These should be correct if the inserts worked
		ASSERT_EQUALS("{0,7,14}", test.toString());
		ASSERT_EQUALS("{14,7,0}", test.toReverseString());

		// Try one remove
		test.pop_back();
		// List should now have a size of 2
		ASSERT_EQUALS(2U, test.size());
		// List should now have these values
		ASSERT_EQUALS("{0,7}", test.toString());
		ASSERT_EQUALS("{7,0}", test.toReverseString());

		// Try another remove
		test.pop_back();
		// List should now have a size of 1
		ASSERT_EQUALS(1U, test.size());
		// List should now have these values
		ASSERT_EQUALS("{0}", test.toString());
		ASSERT_EQUALS("{0}", test.toReverseString());

		// Try last remove (both head and tail should be null)
		test.pop_back();
		// List should now have a size of 0
		ASSERT_EQUALS(0U, test.size());
		// List should now be empty
		ASSERT_EQUALS("{}", test.toString());
		ASSERT_EQUALS("{}", test.toReverseString());
	}

	void testClear()
	{
		ITPDoubleList<int> test;

		for (int i = 0; i < 20; i++)
		{
			test.push_front(i * 5);
		}

		// List should now have a size of 20
		ASSERT_EQUALS(20U, test.size());

		test.clear();

		// List should now have a size of 0
		ASSERT_EQUALS(0U, test.size());
		// List should now be empty (this tests that head/tail are now null)
		ASSERT_EQUALS("{}", test.toString());
		ASSERT_EQUALS("{}", test.toReverseString());
	}

	void testCopyConstructor()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 10; i++)
		{
			test.push_back(i * 2);
		}

		ITPDoubleList<int> copy(test);

		// Size of copy should be 10
		ASSERT_EQUALS(10U, copy.size());

		// Copy should contain these values
		ASSERT_EQUALS("{0,2,4,6,8,10,12,14,16,18}", copy.toString());
		ASSERT_EQUALS("{18,16,14,12,10,8,6,4,2,0}", copy.toReverseString());
	}

	void testAssignment()
	{
		ITPDoubleList<int> test;
		for (int i = 0; i < 10; i++)
		{
			test.push_back(i * 2);
		}

		ITPDoubleList<int> copy;

		// Let's add stuff to copy first
		for (int i = 0; i < 5; i++)
		{
			copy.push_back(i * 7);
		}

		copy = test;

		// Size of copy should be 10
		ASSERT_EQUALS(10U, copy.size());

		// Copy should contain these values
		ASSERT_EQUALS("{0,2,4,6,8,10,12,14,16,18}", copy.toString());
		ASSERT_EQUALS("{18,16,14,12,10,8,6,4,2,0}", copy.toReverseString());
	}
    
    void testIterator()
    {
        ITPDoubleList<int> test;
        for (int i = 5; i < 10; i++)
        {
            test.push_back(i * 2);
        }

        // Create iterators...
        ITPDoubleList<int>::Iterator it1 = test.begin();
        
        // Try to use them...
        ASSERT_EQUALS(10, *it1)
    }
    
   void testIteratorIncDec()
    {
        const int STOP = 10;
        ITPDoubleList<int> test;
        for (int i = 0; i < STOP; i++)
        {
            test.push_back(i * 2);
        }
        
        // Check pre-increment and dereference
        ITPDoubleList<int>::Iterator it1 = test.begin();
        ITPDoubleList<int>::Iterator pit1;
        for (int j = 0; j < STOP; j++)
        {
            if (j == STOP - 1)
            {
                pit1 = it1;
            }
            ASSERT_EQUALS(j * 2, *it1);
            ++it1;
        }
        
        // Check pre-decrement and dereference
        for (int j = STOP - 1; j >= 0; j--)
        {
            ASSERT_EQUALS(j * 2, *pit1);
            --pit1;
        }
        
        // Check post-increment and comparison
        ITPDoubleList<int>::Iterator it2 = test.begin();
        ITPDoubleList<int>::Iterator pit2;
        int k = 0;
        while (it2 != test.end())
        {
            if (k == STOP - 1)
            {
                pit2 = it2;
            }
            ASSERT_EQUALS(k * 2, *it2);
            it2++;
            k++;
        }
        
        // Check post-decrement and comparison
        k = STOP - 1;
        while (pit2 != test.begin())
        {
            ASSERT_EQUALS(k * 2, *pit2);
            pit2--;
            k--;
        }
    }
    
    void testIteratorInsert()
    {
        const int STOP = 5;
        ITPDoubleList<int> test;
        for (int i = 0; i < STOP; i++)
        {
            test.push_back(i * 2);
        }
        
        ITPDoubleList<int>::Iterator it1 = test.begin();
        int num = 42;
        it1 = test.insert(it1, num);
        ASSERT_EQUALS(6U, test.size());
        ASSERT_EQUALS("{42,0,2,4,6,8}", test.toString());

        it1++;
        it1++;
        it1++;
        
        it1 = test.insert(it1, ++num);
        ASSERT_EQUALS(7U, test.size());
        ASSERT_EQUALS("{42,0,2,43,4,6,8}", test.toString());

        it1++;
        it1++;
        it1++;
        
        it1 = test.insert(it1, ++num);
        ASSERT_EQUALS(8U, test.size());
        ASSERT_EQUALS("{42,0,2,43,4,6,44,8}", test.toString());
    }
    
    void testIteratorRemove()
    {
        const int STOP = 10;
        ITPDoubleList<int> test;
        for (int i = 0; i < STOP; i++)
        {
            test.push_back(i * 2);
        }
        
        ASSERT_EQUALS(10U, test.size());
        ASSERT_EQUALS("{0,2,4,6,8,10,12,14,16,18}", test.toString());
        
        ITPDoubleList<int>::Iterator it1 = test.begin();
        it1 = test.erase(it1);
        ASSERT_EQUALS(9U, test.size());
        ASSERT_EQUALS("{2,4,6,8,10,12,14,16,18}", test.toString());

        it1++;
        it1++;
        it1++;
        it1++;
        it1 = test.erase(it1);
        ASSERT_EQUALS(8U, test.size());
        ASSERT_EQUALS("{2,4,6,8,12,14,16,18}", test.toString());
        
        it1++;
        it1++;
		it1++;
        it1 = test.erase(it1);
        ASSERT_EQUALS(7U, test.size());
        ASSERT_EQUALS("{2,4,6,8,12,14,16}", test.toString());
        
    }
};

REGISTER_FIXTURE(ListTest);
